
# Habilita o deshabilita la recolección de métricas de rendimiento (tiempos de ejecución).
# Valores posibles: 'true' (habilitado) o 'false' (deshabilitado).
app.metrics.enabled=true


# SFTP Accounts for Development
sftp.accounts=account1,account2

sftp.account1.host=sftp.dev.example.com
sftp.account1.port=22
sftp.account1.username=devuser1
sftp.account1.password=devpass1
sftp.account1.directory=/dev/remote/dir1

sftp.account2.host=sftp.dev.another.com
sftp.account2.port=22
sftp.account2.username=devuser2
sftp.account2.password=devpass2
sftp.account2.directory=/dev/remote/dir2
