
# Habilita o deshabilita la recolección de métricas de rendimiento (tiempos de ejecución).
# Valores posibles: 'true' (habilitado) o 'false' (deshabilitado).
app.metrics.enabled=true

# SFTP Accounts for Production
sftp.accounts=account1,account2

sftp.account1.host=sftp.prod.example.com
sftp.account1.port=22
sftp.account1.username=produser1
sftp.account1.password=prodpass1
sftp.account1.directory=/prod/remote/dir1

sftp.account2.host=sftp.prod.another.com
sftp.account2.port=22
sftp.account2.username=produser2
sftp.account2.password=prodpass2
sftp.account2.directory=/prod/remote/dir2
